"""criar tabela de usuarios

Revision ID: b0ab6b434cc6
Revises: 
Create Date: 2026-06-04 10:24:25.140106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ab6b434cc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('adversarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('escudo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('ano_fundacao', sa.Integer(), nullable=True),
    sa.Column('escudo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temporadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('posicao', sa.String(length=30), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('adversario_id', sa.Integer(), nullable=False),
    sa.Column('data_partida', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.Column('local', sa.String(length=150), nullable=True),
    sa.Column('competicao', sa.String(length=100), nullable=True),
    sa.Column('rodada', sa.String(length=40), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('mandante', sa.Boolean(), nullable=True),
    sa.Column('gols_pro', sa.Integer(), nullable=True),
    sa.Column('gols_contra', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['adversario_id'], ['adversarios.id'], ),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estatisticas_jogador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('jogos', sa.Integer(), nullable=True),
    sa.Column('gols', sa.Integer(), nullable=True),
    sa.Column('assistencias', sa.Integer(), nullable=True),
    sa.Column('cartoes_amarelos', sa.Integer(), nullable=True),
    sa.Column('cartoes_vermelhos', sa.Integer(), nullable=True),
    sa.Column('pontos_ranking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estatisticas_partida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('participou', sa.Boolean(), nullable=True),
    sa.Column('gols', sa.Integer(), nullable=True),
    sa.Column('assistencias', sa.Integer(), nullable=True),
    sa.Column('cartoes_amarelos', sa.Integer(), nullable=True),
    sa.Column('cartoes_vermelhos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.Column('partida_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_evento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico')
    op.drop_table('estatisticas_partida')
    op.drop_table('estatisticas_jogador')
    op.drop_table('partidas')
    op.drop_table('jogadores')
    op.drop_table('temporadas')
    op.drop_table('times')
    op.drop_table('adversarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
